"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, Banknote, Plus, Wallet } from "lucide-react";
import { useAuth } from "@/lib/auth";
import { apiRequest, formatDate, formatMoney } from "@/lib/api";
import type { Account, Payment, Transfer } from "@/lib/types";
import { Empty, Loading, StatusBadge } from "@/components/ui";

export default function DashboardPage() {
  const { token } = useAuth();
  const accounts = useQuery({ queryKey: ["accounts", token], queryFn: () => apiRequest<Account[]>(token!, "/api/accounts") });
  const transfers = useQuery({ queryKey: ["transfers", token], queryFn: () => apiRequest<Transfer[]>(token!, "/api/transfers") });
  const payments = useQuery({ queryKey: ["payments", token], queryFn: () => apiRequest<Payment[]>(token!, "/api/payments") });
  const currencies = new Set((accounts.data ?? []).map(a => a.currency));
  const balances = [...currencies].map(currency => ({ currency, amount: (accounts.data ?? []).filter(a => a.currency === currency).reduce((sum, a) => sum + a.balance, 0) }));
  const activity = [...(transfers.data ?? []).map(item => ({ id: item.id, title: "Transferencia", status: item.status, currency: item.currency, amount: item.amount, createdAt: item.createdAt, kind: "transfer" })), ...(payments.data ?? []).map(item => ({ id: item.id, title: "Pago", status: item.status, currency: item.currency, amount: item.amount, createdAt: item.createdAt, kind: "payment" }))].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 5);
  const busy = accounts.isPending || transfers.isPending || payments.isPending;
  return <><div className="welcome-row"><div><p className="eyebrow">Tu resumen</p><h1>Hola, qué bueno verte.</h1><p>Este es el estado actual de tu espacio FinPay.</p></div><Link className="date-pill" href="/accounts"><Plus size={14} /> Nueva cuenta</Link></div>
    {busy ? <Loading /> : <><div className="stats-grid">{balances.length ? balances.map(item => <article className="stat-card" key={item.currency}><div className="stat-top"><span>Saldo en {item.currency}</span><span className="stat-icon"><Wallet size={17} /></span></div><div className="stat-value">{formatMoney(item.amount, item.currency)}</div><div className="stat-foot">En {accounts.data?.filter(a => a.currency === item.currency).length} cuenta(s)</div></article>) : <article className="stat-card"><div className="stat-top"><span>Tus cuentas</span><span className="stat-icon"><Wallet size={17} /></span></div><div className="stat-value">0</div><div className="stat-foot">Crea una cuenta para empezar</div></article>}<article className="stat-card"><div className="stat-top"><span>Transferencias</span><span className="stat-icon"><ArrowLeftRight size={17} /></span></div><div className="stat-value">{transfers.data?.length ?? 0}</div><div className="stat-foot">Operaciones registradas</div></article><article className="stat-card"><div className="stat-top"><span>Pagos</span><span className="stat-icon"><Banknote size={17} /></span></div><div className="stat-value">{payments.data?.length ?? 0}</div><div className="stat-foot">Pagos registrados</div></article></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-header"><div><h2 className="panel-title">Tus cuentas</h2><p className="panel-subtitle">Saldos y estado de tus cuentas</p></div><Link className="text-link" href="/accounts">Ver todas <ArrowUpRight size={13} /></Link></div>{accounts.data?.length ? <div className="account-list">{accounts.data.slice(0, 5).map(a => <div className="account-row" key={a.id}><span className="account-symbol"><Wallet size={17} /></span><div className="account-main"><strong>{a.accountNumber}</strong><span>{a.currency} · <StatusBadge status={a.status} /></span></div><div className="account-balance"><strong>{formatMoney(a.balance, a.currency)}</strong><span>Saldo disponible</span></div></div>)}</div> : <Empty title="Aún no tienes cuentas" detail="Crea tu primera cuenta para explorar el panel." />}</section><section className="panel"><div className="panel-header"><div><h2 className="panel-title">Actividad reciente</h2><p className="panel-subtitle">Tus últimas operaciones</p></div><Link className="text-link" href="/transactions">Ver actividad <ArrowUpRight size={13} /></Link></div>{activity.length ? <div className="activity-list">{activity.map(item => <div className="activity-row" key={`${item.kind}-${item.id}`}><span className="activity-icon">{item.kind === "payment" ? <Banknote size={15} /> : <ArrowDownLeft size={15} />}</span><div className="activity-main"><strong>{item.title} <StatusBadge status={item.status} /></strong><span>{formatDate(item.createdAt)}</span></div><span className="activity-amount">{formatMoney(item.amount, item.currency)}</span></div>)}</div> : <Empty title="Todo tranquilo por aquí" detail="Cuando hagas operaciones, aparecerán en esta lista." />}</section></div></>}</>;
}
