spring.application.name=finpay

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/finpay}
spring.datasource.username=${DB_USERNAME:finpay}
spring.datasource.password=${DB_PASSWORD:finpay_dev}

spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=finpay
spring.flyway.default-schema=finpay

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
