"use client";
import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeftRight, Send } from "lucide-react";
import { useAuth } from "@/lib/auth";
import { apiRequest, formatDate, formatMoney } from "@/lib/api";
import type { Account, Transfer } from "@/lib/types";
import { Empty, ErrorBox, Loading, PageHeading, StatusBadge } from "@/components/ui";

export default function TransfersPage() {
  const { token } = useAuth(); const qc = useQueryClient(); const [source, setSource] = useState(""); const [destination, setDestination] = useState(""); const [amount, setAmount] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const accounts = useQuery({ queryKey: ["accounts", token], queryFn: () => apiRequest<Account[]>(token!, "/api/accounts") });
  const transfers = useQuery({ queryKey: ["transfers", token], queryFn: () => apiRequest<Transfer[]>(token!, "/api/transfers") });
  const eligible = (accounts.data ?? []).filter(a => a.status === "ACTIVE");
  const mutation = useMutation({ mutationFn: () => apiRequest<Transfer>(token!, "/api/transfers", { method: "POST", body: JSON.stringify({ sourceAccountId: source, destinationAccountId: destination.trim(), amount: Number(amount) }) }), onSuccess: item => { setError(""); setSuccess(`Transferencia ${item.id} registrada.`); setAmount(""); void qc.invalidateQueries({ queryKey: ["accounts"] }); void qc.invalidateQueries({ queryKey: ["transfers"] }); void qc.invalidateQueries({ queryKey: ["payments"] }); }, onError: e => { setSuccess(""); setError(e instanceof Error ? e.message : "No se pudo realizar la transferencia."); } });
  function submit(e: FormEvent) { e.preventDefault(); setError(""); setSuccess(""); mutation.mutate(); }
  return <><PageHeading eyebrow="Movimientos" title="Transferencias" description="Envía fondos entre cuentas de FinPay en la misma moneda." />
    <div className="section-grid"><section className="panel"><div className="panel-header"><div><h2 className="panel-title">Historial de transferencias</h2><p className="panel-subtitle">Operaciones iniciadas desde tu usuario</p></div><ArrowLeftRight size={17} color="#4d8b73" /></div>{transfers.isPending ? <Loading /> : transfers.data?.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Fecha</th><th>Origen</th><th>Destino</th><th>Importe</th><th>Estado</th></tr></thead><tbody>{transfers.data.map(t => <tr key={t.id}><td>{formatDate(t.createdAt)}</td><td title={t.sourceAccountId}>{t.sourceAccountId.slice(0, 8)}…</td><td title={t.destinationAccountId}>{t.destinationAccountId.slice(0, 8)}…</td><td><strong>{formatMoney(t.amount, t.currency)}</strong></td><td><StatusBadge status={t.status} /></td></tr>)}</tbody></table></div> : <Empty title="Sin transferencias" detail="Las transferencias que inicies aparecerán aquí." />}</section>
    <aside className="panel form-panel"><h2>Nueva transferencia</h2><p>La cuenta de destino se identifica con su ID, que puedes copiar desde la página de cuentas.</p><form onSubmit={submit}><div className="field"><label htmlFor="source">Cuenta de origen</label><select id="source" required value={source} onChange={e => setSource(e.target.value)}><option value="">Selecciona una cuenta</option>{eligible.map(a => <option key={a.id} value={a.id}>{a.accountNumber} · {a.currency} · {formatMoney(a.balance, a.currency)}</option>)}</select></div><div className="field"><label htmlFor="destination">ID de cuenta de destino</label><input id="destination" required value={destination} onChange={e => setDestination(e.target.value)} placeholder="UUID de la cuenta" /></div><div className="field"><label htmlFor="amount">Importe</label><input id="amount" required type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0,00" /></div>{error && <ErrorBox message={error} />}{success && <div className="notice success-note">{success}</div>}<button className="primary-button wide" disabled={!eligible.length || !source || mutation.isPending}><Send size={15} />{mutation.isPending ? "Enviando…" : "Enviar transferencia"}</button></form>{accounts.data?.length === 0 && <div className="notice" style={{ marginTop: 18 }}>Primero crea una cuenta. Las cuentas nuevas no tienen saldo.</div>}</aside></div></>;
}
